name: Deveon_Ideas
version: 1.0
api-version: 1.16
main: me.deveon.quick_ideas.main.Main
authors:
  - Spirol9
website: https://www.youtube.com/c/DeVeon
description: Plugin full of my wonderful video ideas.
depend:
  []
commands:
  DeVeon:
    description: Enable differnt modules.
    aliases: [yt]
  WheelOfPrizesAdmin:
    description: Spin the wheel get a prize.
    aliases: [wopa]
  Timer:
    description: Start timer.
    aliases: [timer]